// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD01kIzv0UuX2TT7sl6aPrI5TdK-J0tIM',
    appId: '1:215887602352:web:3c33de2946873bb22b9175',
    messagingSenderId: '215887602352',
    projectId: 'minimal-social-app-1e6f0',
    authDomain: 'minimal-social-app-1e6f0.firebaseapp.com',
    storageBucket: 'minimal-social-app-1e6f0.firebasestorage.app',
    measurementId: 'G-7F5BBPWPZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL1STbRr-3yDbIil4F3X9bWmFjLZeoBQA',
    appId: '1:215887602352:android:63b1f7be9567a68b2b9175',
    messagingSenderId: '215887602352',
    projectId: 'minimal-social-app-1e6f0',
    storageBucket: 'minimal-social-app-1e6f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgrYbKnjynIfqwY0PJ47N87wSee7vEsbA',
    appId: '1:215887602352:ios:f10810344b6bdba92b9175',
    messagingSenderId: '215887602352',
    projectId: 'minimal-social-app-1e6f0',
    storageBucket: 'minimal-social-app-1e6f0.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgrYbKnjynIfqwY0PJ47N87wSee7vEsbA',
    appId: '1:215887602352:ios:f10810344b6bdba92b9175',
    messagingSenderId: '215887602352',
    projectId: 'minimal-social-app-1e6f0',
    storageBucket: 'minimal-social-app-1e6f0.firebasestorage.app',
    iosBundleId: 'com.example.socialmediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD01kIzv0UuX2TT7sl6aPrI5TdK-J0tIM',
    appId: '1:215887602352:web:bf9df22fd7c26ed92b9175',
    messagingSenderId: '215887602352',
    projectId: 'minimal-social-app-1e6f0',
    authDomain: 'minimal-social-app-1e6f0.firebaseapp.com',
    storageBucket: 'minimal-social-app-1e6f0.firebasestorage.app',
    measurementId: 'G-0X2KW40YBV',
  );
}
